# -*- coding: utf-8 -*-
"""Generate docs/TOOLS.md from tools/registry.py + tools/ast_facts.py.

    AST / decorators / source  ->  derived facts  ->  registry validation  ->  generated docs

This script is the last step. Output is deterministic - every collection is
explicitly sorted, so the result does not depend on filesystem enumeration
order, dict insertion order, the invocation directory, or locale.

Usage:
    python scripts/gen_tool_docs.py            # (re)writes docs/TOOLS.md
    python scripts/gen_tool_docs.py --check     # exits non-zero if docs/TOOLS.md
                                                 # is not byte-identical to what
                                                 # would be generated right now;
                                                 # never modifies any file
"""
import os
import sys

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
MCP_SERVER_DIR = os.path.dirname(SCRIPTS_DIR)
REPO_ROOT = os.path.dirname(MCP_SERVER_DIR)
sys.path.insert(0, MCP_SERVER_DIR)

from tools import ast_facts  # noqa: E402
from tools.registry import TOOLS  # noqa: E402

OUTPUT_PATH = os.path.join(REPO_ROOT, "docs", "TOOLS.md")

CATEGORY_TITLES = {
    "creation": "Creation",
    "query": "Query",
    "editing": "Editing",
    "analysis": "Analysis",
    "documentation": "Documentation",
    "interop": "Interop & persistence",
    "advanced": "Advanced",
}
CATEGORY_ORDER = ["creation", "query", "editing", "analysis", "documentation", "interop", "advanced"]


def _normalize_path(p):
    if p is None:
        return None
    import re
    p = re.sub(r"/<[^>]+>", "/<param>", p)
    p = re.sub(r"/\{\}", "/<param>", p)
    return p


def _build_rows():
    """One row per tool: (name, module, summary, route_path, methods,
    category, risk, mutating, contract). Deterministic - callers sort."""
    tool_to_module = ast_facts.all_tools()
    summaries = ast_facts.all_tool_summaries()
    endpoints = ast_facts.all_tool_endpoints()
    routes = ast_facts.all_routes()
    path_to_route = {}
    for route_file, path, methods, _fn in routes:
        path_to_route[_normalize_path(path)] = (route_file, path, methods)

    rows = []
    for name, entry in TOOLS.items():
        module = tool_to_module.get(name, "?")
        summary = summaries.get(name, "")
        eps = endpoints.get(name, [])
        ep = eps[0] if eps else None
        route_file, route_path, methods = path_to_route.get(
            _normalize_path(ep), ("?", ep or "?", ())
        )
        rows.append(
            (
                name,
                module,
                summary,
                route_file,
                route_path,
                "/".join(methods) if methods else "?",
                entry["category"],
                entry["risk"],
                entry["mutating"],
                entry["contract"],
            )
        )
    return rows


def generate():
    rows = _build_rows()
    total = len(rows)
    categories_used = sorted({r[6] for r in rows})

    lines = []
    lines.append("# Tool registry")
    lines.append("")
    lines.append(
        "**Generated by `scripts/gen_tool_docs.py` from `tools/registry.py` + "
        "`tools/ast_facts.py` - do not hand-edit.** Run `python "
        "scripts/gen_tool_docs.py` after adding or removing a tool; "
        "`tests/test_tool_registry.py` fails the build if this file drifts "
        "from the source it was generated from."
    )
    lines.append("")
    lines.append(
        "**{} tools, {} categories.**".format(total, len(categories_used))
    )
    lines.append("")

    for cat in CATEGORY_ORDER:
        cat_rows = sorted((r for r in rows if r[6] == cat), key=lambda r: r[0])
        if not cat_rows:
            continue
        lines.append("## {} ({})".format(CATEGORY_TITLES[cat], len(cat_rows)))
        lines.append("")
        lines.append("| Tool | Description | Route | Risk | Mutates model | Contract |")
        lines.append("|---|---|---|---|---|---|")
        for name, module, summary, route_file, route_path, methods, category, risk, mutating, contract in cat_rows:
            contract_display = contract if contract == "documented" or contract == "read_only" else contract.split(":", 1)[0]
            lines.append(
                "| `{}` | {} | `{} {}` | {} | {} | {} |".format(
                    name,
                    summary or "_(no docstring)_",
                    methods,
                    route_path,
                    risk,
                    "yes" if mutating else "no",
                    contract_display,
                )
            )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Full contract text (preconditions, post-conditions, verification "
        "method, known limits) for every documented mutating tool lives in "
        "[operation-contracts.md](operation-contracts.md). A `contract` value "
        "starting `known_gap` or `out_of_scope` links back to "
        "`tools/registry.py`'s own comment for the reason."
    )
    lines.append("")

    return "\n".join(lines)


def main():
    check_only = "--check" in sys.argv
    content = generate()

    if check_only:
        if not os.path.exists(OUTPUT_PATH):
            print("docs/TOOLS.md does not exist - run without --check to generate it.")
            return 1
        with open(OUTPUT_PATH, "r", encoding="utf-8") as f:
            existing = f.read()
        if existing != content:
            print("docs/TOOLS.md is stale - run 'python scripts/gen_tool_docs.py' to regenerate.")
            return 1
        print("docs/TOOLS.md is up to date.")
        return 0

    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print("Wrote {}".format(OUTPUT_PATH))
    return 0


if __name__ == "__main__":
    sys.exit(main())
